llm:
  research:
    provider: gpt-turbo
    model: gpt-3.5-turbo
  coding:
    provider: gpt-turbo
    model: gpt-3.5-turbo
  testing:
    provider: gpt-turbo
    model: gpt-3.5-turbo
  dashboard:
    provider: gpt-turbo
    model: gpt-3.5-turbo
  alert:
    provider: gpt-turbo
    model: gpt-3.5-turbo
    
go_tools:
  format:
    command: gofmt
    args: ["-w"]
  vet:
    command: go
    args: ["vet"]
  lint:
    command: golint
    args: []
  security:
    command: gosec
    args: ["-exclude=G104", "./..."]

app_settings:
  max_retries: 3
  test_timeout: 60
  module_name: aws_connect_exporter
